# Generated by Django 5.2.1 on 2025-06-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_size_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ram',
            old_name='size',
            new_name='ram',
        ),
    ]
