# Generated by Django 5.2.1 on 2025-06-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_size_ram_ram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ram',
            old_name='ram',
            new_name='size',
        ),
    ]
