# Generated by Django 5.2.1 on 2025-06-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_ram_ram_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='amount_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
